### ISSUE TITLE
Limit the character length of a Tweet message

### ISSUE THREAD

**Issue by shivapoudel** [themegrill/easy-social-sharing#2]
Tweet message has character length limit so we have to cut off the string length:

TODOS:

- [ ] Shorten the URL used
- [ ] Limit length of tweet message
- [ ]  Maybe reduce the username if too long

CC @sanjipshah

**Comment by shivapoudel** [comment]
Helpful solution to reduce lenth of tweet message:

```
 * Limit length of a tweet message.
 *
 * @param  string  $string
 * @param  integer $limit
 * @return string
 */
function tweet_limit_length( $string, $limit = 100 ) {
	if ( strlen( $string ) > $limit ) {
		$string = substr( $string, 0, $limit - 3 ) . '...';
	}
	return $string;
}
```
